version: "3.9"

services:
  postgres:
    image: postgres:15 # Replace '15' with the version of PostgreSQL you need
    container_name: my_postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demodatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
